create table users(
	id integer GENERATED BY DEFAULT AS IDENTITY,
	name varchar(100) not null,
	firstName varchar(100) not null,
	email varchar(100) not null,
	password varchar(100) not null
)
;

create table topics(
	id integer GENERATED BY DEFAULT AS IDENTITY,
	title varchar(200) not null,
	creatorId integer not null,
    publicTopic bit default 1
)
;

create table messages(
	id integer GENERATED BY DEFAULT AS IDENTITY,
	text varchar(5000) not null,
	dateAndTime datetime not null,
	ownerId integer not null,
	topicId integer not null,
	constraint owner_fk foreign key (ownerId) references users(id) on delete cascade,
	constraint topic_fk foreign key (topicId) references topics(id) on delete cascade
)
;

create table shares(
	id integer GENERATED BY DEFAULT AS IDENTITY,
	topicId integer not null,
	readerId integer not null,
	constraint topic_fk2 foreign key (topicId) references topics(id) on delete cascade,
	constraint reader_fk foreign key (readerId) references users(id) on delete cascade
)
;
